export interface ProjectSnippet {
  projectId: string;
  filename: string;
  language: "typescript" | "python";
  rawLines: string[];
}

export const PROJECT_SNIPPETS: ProjectSnippet[] = [
  {
    projectId: "hiliosai-landing-sales-agent",
    filename: "app/api/agent/route.ts",
    language: "typescript",
    rawLines: [
      "// HiliosAI — AI Lead Capture Agent",
      "import { anthropic } from '@ai-sdk/anthropic'",
      "import { streamText, tool } from 'ai'",
      "import { z } from 'zod'",
      "",
      "export async function POST(req: Request) {",
      "  const { messages } = await req.json()",
      "  const result = streamText({",
      "    model: anthropic('claude-haiku-4-5'),",
      "    system: 'You are an AI sales agent for HiliosAI...',",
      "    messages,",
      "    tools: {",
      "      captureIntent: tool({",
      "        parameters: z.object({ email: z.string().email() }),",
      "      }),",
      "    },",
      "  })",
      "  return result.toDataStreamResponse()",
      "}",
    ],
  },
  {
    projectId: "ai-agents-enrollment",
    filename: "enrollment/agent.py",
    language: "python",
    rawLines: [
      "# AI Agents Enrollment Platform — RAG Classifier",
      "from langchain.agents import AgentExecutor",
      "from langchain.tools import tool",
      "from app.rag import retrieve_context",
      "",
      "@tool",
      "def classify_enrollment(query: str) -> str:",
      '    """Classify enrollment intent using RAG"""',
      "    context = retrieve_context(query)",
      "    return enrollment_llm.invoke(context)",
      "",
      "async def run_agent(message: str):",
      "    agent = AgentExecutor(",
      "        agent=enrollment_agent,",
      "        tools=[classify_enrollment],",
      "    )",
      "    return await agent.arun(message)",
    ],
  },
  {
    projectId: "gymintelops",
    filename: "lib/gym/automation.ts",
    language: "typescript",
    rawLines: [
      "// GymIntelOps — AI Marketing Automation",
      "import { db } from '@/lib/db'",
      "import { generateContent } from '@/lib/ai'",
      "import { sendEmail } from '@/lib/email'",
      "",
      "export async function runRetentionCampaign(gymId: string) {",
      "  const atRisk = await db.member.findMany({",
      "    where: { gymId, churnRisk: 'high' },",
      "  })",
      "",
      "  for (const member of atRisk) {",
      "    const content = await generateContent({",
      "      type: 'retention_email',",
      "      member,",
      "    })",
      "    await sendEmail(member.email, content)",
      "  }",
      "}",
    ],
  },
];
