export const siteConfig = {
  name: "Le Thanh Phong | Software Engineer",
  authorName: "Le Thanh Phong",
  username: "PhongLee1210",
  description:
    "I'm a senior software engineer with 5+ years of experience in the industry, specializing in building scalable and efficient web applications. I'm a quick learner and always looking for new challenges and opportunities to grow.",
  url: "https://phonghub-cloud.vercel.app",
  links: {
    twitter: "https://x.com/phonglee802q",
    github: "https://github.com/PhongLee1210",
    resume:
      process.env.NEXT_PUBLIC_RESUME_LINK ||
      "https://rxresu.me/phonglee1210/5-yrs-full-stack-engineer",
  },
  ogImage: "/me.JPG",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Le Thanh Phong",
    "Phong Lee",
    "Software Engineer",
    "Full Stack Developer",
    "DevOps Engineer",
    "AI Engineer",
    "Web Developer",
    "Next.js",
    "React",
    "Developer",
    "Next.js",
    "Modern website",
    "Frontend developer",
    "Full stack developer",
    "Open source",
    "Web developer",
    "Responsive",
    "React.js",
    "Tailwind CSS",
    "Developer showcase",
    "Vietnamese Developer",
  ],
};
